USE [LYBK]
GO

/****** Object:  Table [dbo].[CONSUMIDO]    Script Date: 27/10/2017 05:48:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CONSUMIDO](
	[FCS_ID] [uniqueidentifier] NOT NULL,
	[PAQUETEID] [nvarchar](20) NOT NULL,
	[CENTRO_TRABAJO] [nvarchar](10) NULL,
	[NRO_ORDEN] [nvarchar](20) NULL,
	[CANTIDAD_CONSUMIDA] [decimal](9, 3) NOT NULL,
	[UNIDAD] [nvarchar](4) NOT NULL,
	[STATUS] [nvarchar](4) NULL,
	[FECHA] [datetime] NULL,
	[FCS_BATCH_LABEL_1] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_CONSUMIDO] PRIMARY KEY CLUSTERED 
(
	[FCS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


